# Generated by Django 5.0.6 on 2024-06-19 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackendService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=50)),
                ('service_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_type', models.CharField(max_length=50)),
                ('connection_string', models.CharField(max_length=256)),
                ('credentials', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_type', models.CharField(max_length=50)),
                ('deployment_url', models.URLField()),
                ('credentials', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UIComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=100)),
                ('component_type', models.CharField(max_length=50)),
                ('component_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password_hash', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VersionControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_control_type', models.CharField(max_length=50)),
                ('repository_url', models.URLField()),
                ('credentials', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=50)),
                ('database_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.databaseconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.user')),
                ('version_control', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.versioncontrol')),
            ],
        ),
        migrations.CreateModel(
            name='MobileApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.application')),
                ('deployment_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.deploymentconfig')),
            ],
        ),
        migrations.CreateModel(
            name='WebComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_component_url', models.URLField()),
                ('ui_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.uicomponent')),
            ],
        ),
    ]
